services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: posanmeal
      POSTGRES_PASSWORD: posanmeal
      POSTGRES_DB: posanmeal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
